In [1]:
import pandas as pd
import numpy as np

In [2]:
gap_penalty=-1
match_score=2
mismatch_score=-1

In [3]:
def initialize(r,c):
    mat=np.zeros((r+1,c+1))
    mat[0]=[-i for i in range(len(mat[0]))]
    mat[:,0]=[-i for i in range(len(mat[:,0]))]
    return(mat)

In [4]:
def match(seq1,seq2):
    mat=np.ones((len(seq1),len(seq2)))
    for i in range(len(seq1)):
        for j in range(len(seq2)):
            if(seq1[i]==seq2[j]):
                mat[i,j]=match_score
            else:
                mat[i,j]=mismatch_score
    return(mat)

In [5]:
def backtrack(mat,seq1,seq2,match_table):
    a_a=""
    a_b=""
    i=len(seq1)
    j=len(seq2)
    while(i>0 or j>0):
        if(i>0 and j>0 and mat[i,j]==mat[i-1,j-1]+match_table[i-1,j-1]):
            a_a = seq1[i-1] + a_a
            a_b = seq2[j-1] + a_b
            i = i-1
            j = j-1
        elif(i>0 and mat[i,j]==mat[i-1,j]+gap_penalty):
            a_a = seq1[i-1] + a_a
            a_b = '_' + a_b
            i =i-1
        else:
            a_a = '_' + a_a
            a_b = seq2[j-1] + a_b
            j =j-1            
    return(a_a,a_b)

In [6]:
def matrix(mat,match_table):
    for i in range(1,mat.shape[0]):
        for j in range(1,mat.shape[1]):
            a=mat[i-1,j]+gap_penalty
            b=mat[i,j-1]+gap_penalty
            c=mat[i-1,j-1]+match_table[i-1,j-1]
            mat[i,j]=max(a,b,c)
    return(mat)

In [7]:
def n_w(seq1,seq2):
    seq1=seq1.lower()
    seq2=seq2.lower()
    mat=initialize(len(seq1),len(seq2))
    match_table=match(seq1,seq2)
    mat=matrix(mat,match_table)
    alignment=backtrack(mat,seq1,seq2,match_table)
    print(mat)
    return(alignment)

# Example

In [8]:
n_w('GLYCINE','CYSTEINE')

[[ 0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-1. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-2. -2. -2. -3. -4. -5. -6. -7. -8.]
 [-3. -3.  0. -1. -2. -3. -4. -5. -6.]
 [-4. -1. -1. -1. -2. -3. -4. -5. -6.]
 [-5. -2. -2. -2. -2. -3. -1. -2. -3.]
 [-6. -3. -3. -3. -3. -3. -2.  1.  0.]
 [-7. -4. -4. -4. -4. -1. -2.  0.  3.]]


('gly__cine', '_cysteine')

In [9]:
n_w('GACTTAC','CGTGAATTCAT')

[[  0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10. -11.]
 [ -1.  -1.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.]
 [ -2.  -2.   0.   0.  -1.   1.   0.  -1.  -2.  -3.  -4.  -5.]
 [ -3.   0.  -1.  -1.  -1.   0.   0.  -1.  -2.   0.  -1.  -2.]
 [ -4.  -1.  -1.   1.   0.  -1.  -1.   2.   1.   0.  -1.   1.]
 [ -5.  -2.  -2.   1.   0.  -1.  -2.   1.   4.   3.   2.   1.]
 [ -6.  -3.  -3.   0.   0.   2.   1.   0.   3.   3.   5.   4.]
 [ -7.  -4.  -4.  -1.  -1.   1.   1.   0.   2.   5.   4.   4.]]


('___gactt_ac', 'cgtgaattcat')

In [10]:
n_w('ggttgacta','tgttacgg')

[[ 0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-1. -1.  1.  0. -1. -2. -3. -4. -5.]
 [-2. -2.  1.  0. -1. -2. -3. -1. -2.]
 [-3.  0.  0.  3.  2.  1.  0. -1. -2.]
 [-4. -1. -1.  2.  5.  4.  3.  2.  1.]
 [-5. -2.  1.  1.  4.  4.  3.  5.  4.]
 [-6. -3.  0.  0.  3.  6.  5.  4.  4.]
 [-7. -4. -1. -1.  2.  5.  8.  7.  6.]
 [-8. -5. -2.  1.  1.  4.  7.  7.  6.]
 [-9. -6. -3.  0.  0.  3.  6.  6.  6.]]


('ggttgacta', 'tgtt_acgg')