In [1]:
import pandas as pd
import numpy as np

In [2]:
gap_penalty=-2
match_score=+3
mismatch_score=-4

In [3]:
def initialize(r,c):
    mat=np.zeros((r+1,c+1))
    return(mat)

In [4]:
def match(seq1,seq2):
    mat=np.ones((len(seq1),len(seq2)))
    for i in range(len(seq1)):
        for j in range(len(seq2)):
            if(seq1[i]==seq2[j]):
                mat[i,j]=match_score
            else:
                mat[i,j]=mismatch_score
    return(mat)

In [6]:
def matrix(mat,match_table):
    for i in range(1,mat.shape[0]):
        for j in range(1,mat.shape[1]):
            a=mat[i-1,j]+gap_penalty
            b=mat[i,j-1]+gap_penalty
            c=mat[i-1,j-1]+match_table[i-1,j-1]
            if(max(a,b,c)<0):
                mat[i,j]=0
            else:
                mat[i,j]=max(a,b,c)
    return(mat)

In [7]:
def backtracking(mat,match_table,seq1,seq2):
    max_ele=np.unravel_index(np.argmax(mat, axis=None), mat.shape)
    a=""
    b=""
    i=max_ele[0]
    j=max_ele[1]
    while(mat[i,j]!=0 and (i>0 or j>0)):
        if(i>0 and j>0 and mat[i,j]==mat[i-1,j-1]+match_table[i-1,j-1]):
            a=seq1[i-1]+a
            b=seq1[i-1]+b
            i = i-1
            j = j-1
        elif(i>0 and mat[i,j]==mat[i-1,j]+gap_penalty):
            a='_'+a
            b=seq1[i-1]+b
            i =i-1
        else:
            b = '_' +b
            a=seq2[j-1]+a
            j =j-1
    return(a,b)

In [8]:
def s_w(seq1,seq2):
    seq1=seq1.lower()
    seq2=seq2.lower()
    mat=initialize(len(seq1),len(seq2))
    match_table=match(seq1,seq2)
    mat=matrix(mat,match_table)
    print(mat)
    alignment=backtracking(mat,match_table,seq1,seq2)
    return(alignment)

## Examples

In [9]:
s_w('gcgatata','aacctatagct')

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  1.  0.]
 [ 0.  0.  0.  3.  3.  1.  0.  0.  0.  1.  6.  4.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  0.  3.  4.  2.]
 [ 0.  3.  3.  1.  0.  0.  3.  1.  3.  1.  2.  0.]
 [ 0.  1.  1.  0.  0.  3.  1.  6.  4.  2.  0.  5.]
 [ 0.  3.  4.  2.  0.  1.  6.  4.  9.  7.  5.  3.]
 [ 0.  1.  2.  0.  0.  3.  4.  9.  7.  5.  3.  8.]
 [ 0.  3.  4.  2.  0.  1.  6.  7. 12. 10.  8.  6.]]


('tata', 'tata')

In [10]:
s_w('ggttgacta','tgttacgg')

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  3.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  6.]
 [ 0.  3.  1.  6.  4.  2.  0.  1.  4.]
 [ 0.  3.  1.  4.  9.  7.  5.  3.  2.]
 [ 0.  1.  6.  4.  7.  5.  3.  8.  6.]
 [ 0.  0.  4.  2.  5. 10.  8.  6.  4.]
 [ 0.  0.  2.  0.  3.  8. 13. 11.  9.]
 [ 0.  3.  1.  5.  3.  6. 11.  9.  7.]
 [ 0.  1.  0.  3.  1.  6.  9.  7.  5.]]


('gtt_ac', 'gttgac')

In [11]:
s_w('GACTTAC','CGTGAATTCAT')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 1. 3. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 6. 4. 2. 0. 0. 3. 1.]
 [0. 3. 1. 0. 0. 4. 2. 0. 0. 3. 1. 0.]
 [0. 1. 0. 4. 2. 2. 0. 5. 3. 1. 0. 4.]
 [0. 0. 0. 3. 1. 0. 0. 3. 8. 6. 4. 3.]
 [0. 0. 0. 1. 0. 4. 3. 1. 6. 4. 9. 7.]
 [0. 3. 1. 0. 0. 2. 1. 0. 4. 9. 7. 5.]]


('gacttca', 'gactt_a')